name: Build nightly

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: ["main"]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: skylyrac/blocksds:slim-latest
    name: Build with Docker using BlocksDS
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Make application
        run: |
          make VERBOSE=1
      - name: Prepare for build publishing
        run: |
          mkdir -p ~/artifacts
          cp -f dsbf_dump.nds ~/artifacts/
      - name: Publish build to GH Actions
        uses: actions/upload-artifact@v2
        with:
          path: ~/artifacts/*
          name: build
